service: faker

plugins:
  - serverless-hooks-plugin # see https://www.npmjs.com/package/serverless-hooks-plugin

provider:
  name: aws
  runtime: ruby2.5
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}

custom:
  hooks:
    before:package:initialize:
      - docker-compose run layer-bundle-install
      - docker-compose run bundle-install

package:
  exclude:
    - README.md
    - package.json
    - yarn.lock
    - node_modules/**
    - docker-compose.yml

layers:
  gems:
    path: layers
    # name: ${self:service}-${self:provider.stage}-gems
    compatibleRuntimes:
      - ruby2.5
    allowedAccounts:
      - '*'

functions:
  lorem:
    handler: functions/handler.lorem
    layers:
      - {Ref: GemsLambdaLayer}
