service: lorem

provider:
  name: aws
  runtime: ruby2.5

  stage: dev
  region: ap-northeast-1

layers:
  faker:
    path: layers
    name: faker-gem
    compatibleRuntimes:
      - ruby2.5
    allowedAccounts:
      - '*'

functions:
  lorem:
    handler: functions/handler.lorem
    layers:
      - {Ref: FakerLambdaLayer}
